// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfS0pLzqChRQTBGnOvpkz5tg4E2RwSdpU',
    appId: '1:71584404984:web:ff64eddfd5d0f34df2320d',
    messagingSenderId: '71584404984',
    projectId: 'app-catalogo-peliculas',
    authDomain: 'app-catalogo-peliculas.firebaseapp.com',
    storageBucket: 'app-catalogo-peliculas.firebasestorage.app',
    measurementId: 'G-TN1ZKS17Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzDm-Ti4Uv84CHTjjS_zCX4ZlM-fovfOo',
    appId: '1:71584404984:android:67cd179b5345f70cf2320d',
    messagingSenderId: '71584404984',
    projectId: 'app-catalogo-peliculas',
    storageBucket: 'app-catalogo-peliculas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZ4_pZCXiwI6H7NtOCdvmupDKPd7XzRs',
    appId: '1:71584404984:ios:c747d6085894e3d2f2320d',
    messagingSenderId: '71584404984',
    projectId: 'app-catalogo-peliculas',
    storageBucket: 'app-catalogo-peliculas.firebasestorage.app',
    iosBundleId: 'com.example.ldswUtilizacionWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxZ4_pZCXiwI6H7NtOCdvmupDKPd7XzRs',
    appId: '1:71584404984:ios:c747d6085894e3d2f2320d',
    messagingSenderId: '71584404984',
    projectId: 'app-catalogo-peliculas',
    storageBucket: 'app-catalogo-peliculas.firebasestorage.app',
    iosBundleId: 'com.example.ldswUtilizacionWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfS0pLzqChRQTBGnOvpkz5tg4E2RwSdpU',
    appId: '1:71584404984:web:02a0523fc95af9aaf2320d',
    messagingSenderId: '71584404984',
    projectId: 'app-catalogo-peliculas',
    authDomain: 'app-catalogo-peliculas.firebaseapp.com',
    storageBucket: 'app-catalogo-peliculas.firebasestorage.app',
    measurementId: 'G-F0RN8S614Z',
  );
}
